<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\XDrishti.Application\XDrishti.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <Import Project="..\Tests.props" />
</Project>
