/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/system/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health of the API, database and background services */
    get: operations['GetSystemStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApplicationStatus: {
      name: string;
      version: string;
      environment: string;
      instance: string;
      /** Format: date-time */
      startedAt: string;
      /** Format: int64 */
      uptimeSeconds: number;
    };
    DatabaseStatus: {
      isConnected: boolean;
      serverVersion: null | string;
      timescaleVersion: null | string;
      latestMigration: null | string;
      /** Format: int32 */
      pendingMigrations: number;
      /** Format: double */
      latencyMs: number;
      error: null | string;
    };
    ServiceStatus: {
      name: string;
      instance: string;
      version: string;
      /** Format: date-time */
      startedAt: string;
      /** Format: date-time */
      lastSeenAt: string;
      isAlive: boolean;
    };
    SystemStatusResponse: {
      application: components['schemas']['ApplicationStatus'];
      database: components['schemas']['DatabaseStatus'];
      services: components['schemas']['ServiceStatus'][];
      isHealthy: boolean;
      /** Format: date-time */
      checkedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetSystemStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SystemStatusResponse'];
        };
      };
    };
  };
}
