<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\XDrishti.Api\XDrishti.Api.csproj" />
    <ProjectReference Include="..\..\src\XDrishti.Worker\XDrishti.Worker.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <Import Project="..\Tests.props" />
</Project>
